name: ChrisPieracci
favicon: null
layout_spectrum: 0.6017824267037213
typography_spectrum: 0.180946484208107
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4907021466642618
  lightness: 0.22904441528953612
  saturation: 0.6256666034460068
  rhythmicContrast: 0.6429970448371023
purpose: []
